import type { Metadata } from "next";
import { Montserrat} from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Rimac",
  description: "Generated by create next app",
};

const lato = Montserrat({ 
  weight: [ "200","300","400","500","600"],
  subsets: ["latin"],
 });

export default function RootLayout({children}: Readonly<{children: React.ReactNode}>) {
  return (
    <html lang="en">
      <body className={lato.className}>
        {children}
      </body>
    </html>
  );
}
