import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./styles.css";

export const metadata: Metadata = {
  title: "Rimac",
  description: "Generated by create next app",
};

const lato = Montserrat({
  weight: ["200", "300", "400", "500", "600"],
  subsets: ["latin"],
});

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href={`${process.env.NODE_ENV === 'production' ? '/Rimac-seguros' : ''}/styles.css`} />
      </head>
      <body className={lato.className}>
        {children}
      </body>
    </html>
  );
}
